giantswarm/falco-app

.abs/main.yaml, .circleci/config.yml, .github/pull_request_template.md, README.md, helm/APP-NAME/Chart.yaml, helm/APP-NAME/values.yaml
=> Rename to falco-app

.circleci/config.yml, helm/falco-app/Chart.yaml, helm/falco-app/values.yaml
=> Fix circle

.circleci/config.yml
I think this makes more sense for now.
=> Change catalog to internal one for now

helm/falco-app/charts/falco/values.yaml, helm/falco-app/values.yaml
=> Enable grpc unix socket on falco app

README.md, helm/falco-app/values.yaml
=> Add example custom rules

README.md
=> Add links to upstream website and repo

.circleci/config.yml, CHANGELOG.md
=> Push falco-app to collections on tag

CHANGELOG.md, helm/falco-app/values.yaml
=> Add limits and requests to falco exporter

helm/falco-app/Chart.yaml
=> Bump falcosidekick version

helm/falco-app/Chart.yaml
Bumping version after automated update.
=> Update falco-exporter to latest upstream version

.circleci/config.yml, CHANGELOG.md
=> Do not push to KVM collection

CHANGELOG.md, helm/falco-app/Chart.yaml
Updated the icon to use the logo https://s.giantswarm.io/app-icons/falco/1/dark.svg
<div style="background-color: #333"><img src="https://s.giantswarm.io/app-icons/falco/1/dark.svg" /></div>
=> Update falco icon

helm/falco-app/Chart.yaml
Towards https://github.com/giantswarm/giantswarm/issues/19760
=> Set team annotation in Chart.yaml for app alert routing

CHANGELOG.md
=> Remove old v0.2.0 ref in changelog

CHANGELOG.md, helm/falco-app/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/867
=> Set priorityClass for falco daemonset

CHANGELOG.md
=> Changelog heading

helm/falco-app/templates/update-logic/update-job.yaml
=> Template in ds name

CHANGELOG.md, helm/falco/values.yaml
=> Move Falco PolicyExceptions to `giantswarm` namespace

CHANGELOG.md, helm/falco/values.yaml
Towards: https://github.com/giantswarm/roadmap/issues/2389
=> Replace master with control-plane role on falco and falco-exporter tolerations

helm/falco/Chart.yaml
=> Update Chart versions

CHANGELOG.md, helm/falco/values.schema.json, helm/falco/values.yaml
=> Add falcoctl values

CHANGELOG.md, helm/falco/templates/falco-ciliumnetworkpolicy.yaml, helm/falco/values.schema.json, helm/falco/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/23014
Towards https://github.com/giantswarm/roadmap/issues/1949
=> Add support for Cilium network policies

CHANGELOG.md, helm/falco/Chart.yaml
=> revert changelog

CHANGELOG.md, helm/falco/templates/falco-psp.yaml, helm/falco/values.schema.json, helm/falco/values.yaml
=> Implemented toggle for psps

helm/falco/values.yaml
=> Fixed falcoctl image-value location

CHANGELOG.md, helm/falco/templates/falco-policy-exception.yaml
Towards: giantswarm/roadmap#2900
=> Update Kyverno PolicyExceptions

helm/falco/charts/falco/Chart.yaml
Reverts giantswarm/falco-app#198
=> Revert "Update Helm release falcosidekick to v0.7.11"

helm/falco/charts/falco-exporter/values.yaml
Reverts giantswarm/falco-app#199
=> Revert "Update docker.io/falcosecurity/falco-exporter Docker tag to v0.8.6"

helm/falco/charts/falco/values.yaml
Reverts giantswarm/falco-app#202
=> Revert "Update docker.io/falcosecurity/falcoctl Docker tag to v0.7.0"

CHANGELOG.md, helm/falco/templates/falco-exporter-cilium-network-policy.yaml
towards https://github.com/giantswarm/giantswarm/issues/29581
=> Add CiliumNetworkPolicy for falco-exporter

CHANGELOG.md, helm/falco/values.schema.json, helm/falco/values.yaml
After the upstream changes, resolving breaking changes required for the new major chart version. We can add the teamlabels..
=> Add team labels
